CREATE DATABASE Cinema;
USE Cinema;

CREATE TABLE Movies(
MovieId INT PRIMARY KEY AUTO_INCREMENT,
Title VARCHAR(100) NOT NULL,
ReleaseYear DATE NOT NULL,
Genre VARCHAR(80) 
);

CREATE TABLE Actors(
ActorId INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(100) NOT NULL
);

CREATE TABLE Casting(
CastingId INT PRIMARY KEY AUTO_INCREMENT,
MovieId INT,
ActorId INT,
RoleName VARCHAR(100),
Salary DECIMAL(9,2) NOT NULL,
CONSTRAINT fk_movieid FOREIGN KEY (MovieId) REFERENCES Movies(MovieId),
CONSTRAINT fk_actorid FOREIGN KEY (ActorId) REFERENCES Actors(ActorId),
UNIQUE(MovieId,ActorId)
);


